version: '3'

volumes:
  data_dev: {}

services:
  icd:
    build:
      context: .
      dockerfile: ./compose/icd/Dockerfile-dev
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENVTYPE=dev
    #env-file:
    #  - ./.envs/.dev/.icd
    image: icd:dev
    volumes:
      - .:/app
      - data_dev:/data
    #command: /start
